name = "gaming-gauntlet-edge"
main = "apps/edge/src/index.ts"
compatibility_date = "2026-03-23"
workers_dev = true

[observability.logs]
enabled = true

[vars]
APP_ORIGIN = "http://localhost:5173"
EXTENSION_ORIGIN = "http://localhost:5174"
TWITCH_API_BASE = "https://api.twitch.tv/helix"
TWITCH_CLIENT_ID = "fc5utkuzthjxl2xo28992adi7ymivw"
TWITCH_REDIRECT_URI = "https://gaming-gauntlet-edge.pressplay-subai.workers.dev/api/auth/twitch/callback"


[[d1_databases]]
binding = "DB"
database_name = "gaming-gauntlet"
database_id = "e342c961-37e4-4c5b-9764-0d4f097cfe8b"
migrations_dir = "apps/edge/migrations"

[[durable_objects.bindings]]
name = "MATCH_COORDINATOR"
class_name = "MatchCoordinator"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchCoordinator"]

[[queues.producers]]
binding = "EVENT_INGEST_QUEUE"
queue = "gaming-gauntlet-event-ingest"

[[queues.consumers]]
queue = "gaming-gauntlet-event-ingest"
max_batch_size = 10
max_batch_timeout = 5
