/* eslint-disable */
// Generated by Wrangler by running `wrangler types apps/api/src/worker-configuration.d.ts --config wrangler.api.toml --include-runtime false` (hash: 9ae6956f6097d024e35dada1ccb1604e)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
